api/urls.py
from . import views
from django.urls import path, include
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'customers', views.CustomerViewset)
router.register(r'addresses', views.CustomerAddressViewset)
router.register(r'documents', views.CustomerDocumentViewset)
router.register(r'customers/(?P<customer>[0-9]+)/addresses', views.CustomerAddressViewset, basename='cust-addresses')
router.register(r'customers/(?P<customer>[0-9]+)/documents', views.CustomerDocumentViewset, basename='cust-documents')

# The API URLs are now determined automatically by the router.
app_name = 'api'
urlpatterns = [
    path('login/', views.LoginAPIView.as_view()),
    path('', include(router.urls)),
]

crm/urls.py
from . import views
from django.urls import path

app_name = 'crm'
urlpatterns = [
    path('customers/', views.CustomerListView.as_view(), name='customer-list'),
    path('customers/add/', views.CustomerCreateView.as_view(), name='customer-add'),
    path('customers/<int:pk>/', views.CustomerUpdateView.as_view(), name='customer-modify'),
    path('', views.Dashboard.as_view(), name='dashboard'),
]

tfntest/urls.py
from core.views import GenLoginView, GenLogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls', namespace='api')),
    path('login/', GenLoginView.as_view(), name='login'),
    path('logout/', GenLogoutView.as_view(), name='logout'),
    path('', include('crm.urls', namespace='crm')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
import logging
import pytz
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from rest_framework.authtoken.models import Token
from tfntest.storage import OverrideFileCustomOSStorage


notification_logger = logging.getLogger('notification_logger')
override_file = OverrideFileCustomOSStorage()

class User(AbstractUser):
    language = models.CharField(_('Language'), max_length=2, choices=settings.LANGUAGES, default='en')
    timezone = models.CharField(
        _("timezone"), max_length=100, choices=[(i, i) for i in pytz.common_timezones], default="UTC"
    )
    image = models.ImageField(
        _('Profile Picture'),
        default='defaults/default_profile.jpg',
        upload_to='users/',
        storage=override_file
    )

    def save(self, **kwargs):
        is_new = not self.pk
        super().save(**kwargs)
        if is_new:
            __ = Token.objects.get_or_create(user=self)

core/forms.py
from .models import User
from django import forms

class ModelFormControl(forms.ModelForm):
    form_control_exclude = []

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        allowed_fields = kwargs.pop('fields', [])
        readonly_fields = kwargs.pop('readonly_fields', [])
        super().__init__(*args, **kwargs)
        for field in set(self.fields):
            if field not in allowed_fields:
                print(f'popping field {field}')
                self.fields.pop(field)

        for field in self.fields.keys():
            if field in readonly_fields:
                self.fields[field].widget.attrs['readonly'] = True
            if field in self.form_control_exclude:
                continue
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = User
        fields = '__all__'

core/views.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.views.generic.base import ContextMixin


class GenLoginView(auth_views.LoginView):
    template_name = 'core/login.html'
    redirect_authenticated_user = True


class GenLogoutView(auth_views.LogoutView):
    next_page = 'login'


class NavigationHTML(ContextMixin):
    nav_group_item = None
    nav_group_name = None

    # noinspection PyProtectedMember,PyUnresolvedReferences
    def get_context_data(self, **kwargs):
        if hasattr(self, 'model'):
            kwargs['model'] = self.model
            kwargs['model_meta'] = self.model._meta
            kwargs['nav_group_item'] = self.model._meta.object_name
            kwargs['nav_group_name'] = self.model._meta.app_label
        else:
            kwargs['nav_group_item'] = self.nav_group_item
            kwargs['nav_group_name'] = self.nav_group_name
        return super().get_context_data(**kwargs)


# noinspection PyProtectedMember
class GenListView(NavigationHTML, LoginRequiredMixin, ListView):
    paginate_by = None
    template_name = 'crm/objects_list.html'
    title = '%(verbose_name_plural)s'
    filters = []
    allow_empty = True

    def get_filters_from_request(self):
        # search filters in url if filters do exists change key append __in
        return {f'{k}__in': self.request.GET.getlist(k)
                for k in self.filters if self.request.GET.getlist(k, ['']) != ['']}

    # noinspection PyUnresolvedReferences
    def get_queryset(self):
        filters = self.get_filters_from_request()
        queryset = super().get_queryset()
        if filters:
            queryset = queryset.filter(**filters)
        return queryset

core/templates/core/base.html
<!DOCTYPE html>
{% load static i18n %}
<html lang="en">
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<title>Telefonica | CRM</title>
	<meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />

	<link rel="icon" href="{% static 'core/img/icon.ico' %}" type="image/x-icon"/>

	<!-- Fonts and icons -->
	<script src="{% static 'core/js/plugin/webfont/webfont.min.js' %}"></script>
	<script>
		WebFont.load({
			google: {"families":["Lato:300,400,700,900"]},
			custom: {"families":["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ['{% static 'core/css/fonts.min.css' %}']},
			active: function() {
				sessionStorage.fonts = true;
			}
		});
	</script>

	<!-- CSS Files -->
	<link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'core/css/atlantis.min.css' %}">

	<!-- CSS Just for demo purpose, don't include it in your project -->
	<link rel="stylesheet" href="{% static 'core/css/demo.css' %}">
	{% block head %}{% endblock head %}
</head>
<body>
	<div class="wrapper">
		<div class="main-header">
			{% if request.user.is_authenticated %}
			<!-- Logo Header -->
			<div class="logo-header" data-background-color="blue">
				<a href="{% url 'crm:dashboard' %}" class="logo text-white">Telefonica</a>
				<button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon">
						<i class="icon-menu"></i>
					</span>
				</button>
				<button class="topbar-toggler more"><i class="icon-options-vertical"></i></button>
				<div class="nav-toggle">
					<button class="btn btn-toggle toggle-sidebar">
						<i class="icon-menu"></i>
					</button>
				</div>
			</div>
			<!-- End Logo Header -->

			<!-- Navbar Header -->
			<nav class="navbar navbar-header navbar-expand-lg" data-background-color="blue2">

				<div class="container-fluid">
					<ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
						<li class="nav-item toggle-nav-search hidden-caret">
							<a class="nav-link" data-toggle="collapse" href="#search-nav" role="button" aria-expanded="false" aria-controls="search-nav">
								<i class="fa fa-search"></i>
							</a>
						</li>

						<li class="nav-item dropdown hidden-caret">
							<a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
								<div class="avatar-sm">
									<img src="{{ request.user.image.url }}" alt="..." class="avatar-img rounded-circle">
								</div>
							</a>
							<ul class="dropdown-menu dropdown-user animated fadeIn">
								<div class="dropdown-user-scroll scrollbar-outer">
									<li>
										<div class="user-box">
											<div class="avatar-lg"><img src="{{ request.user.image.url }}" alt="image profile" class="avatar-img rounded"></div>
											<div class="u-text">
												<h4>{{ request.user.first_name }} {{ request.user.last_name }}</h4>
												<p class="text-muted">{{ request.user.email }}</p>
											</div>
										</div>
									</li>
									<li>
										<div class="dropdown-divider"></div>
										<a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
									</li>
								</div>
							</ul>
						</li>
					</ul>
				</div>
			</nav>
			<!-- End Navbar -->
			{% endif %}
		</div>

		{% if request.user.is_authenticated %}
		<!-- Sidebar -->
		<div class="sidebar sidebar-style-2">
			<div class="sidebar-wrapper scrollbar scrollbar-inner">
				<div class="sidebar-content">
                    <ul class="nav nav-primary">
						<li class="nav-section">
							<span class="sidebar-mini-icon">
								<i class="fa fa-ellipsis-h"></i>
							</span>
						</li>
                        <li class="nav-item" id="crm-nav">
							<a data-toggle="collapse" href="#crm">
								<i class="fas fa-user"></i>
								<p>{% trans 'CRM' %}</p>
								<span class="caret"></span>
							</a>
							<div class="collapse" id="crm">
								<ul class="nav nav-collapse">
									<li id="crmCustomer">
										<a href="{% url 'crm:customer-list' %}">
											<span class="sub-item">{% trans 'Customers' %}</span>
										</a>
									</li>
								</ul>
							</div>
						</li>
                    </ul>
				</div>
			</div>
		</div>
		<!-- End Sidebar -->
		{% endif %}

		<div class="main-panel">
			<div class="content">
				{% block content%}{% endblock content %}
			</div>
			<footer class="footer">
				<div class="container-fluid">
					<div class="copyright ml-auto">
						2022, TELEFONICA MOVILES EL SALVADOR S.A. de C.V.
					</div>
				</div>
			</footer>
		</div>
	</div>
	<!--   Core JS Files   -->
	<script src="{% static 'core/js/core/jquery.3.2.1.min.js' %}"></script>
	<script src="{% static 'core/js/core/popper.min.js' %}"></script>
	<script src="{% static 'core/js/core/bootstrap.min.js' %}"></script>

	<!-- jQuery UI -->
	<script src="{% static 'core/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js' %}"></script>
	<script src="{% static 'core/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js' %}"></script>

	<!-- jQuery Scrollbar -->
	<script src="{% static 'core/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js' %}"></script>


	<!-- Chart JS -->
	<script src="{% static 'core/js/plugin/chart.js/chart.min.js' %}"></script>

	<!-- jQuery Sparkline -->
	<script src="{% static 'core/js/plugin/jquery.sparkline/jquery.sparkline.min.js' %}"></script>

	<!-- Chart Circle -->
	<script src="{% static 'core/js/plugin/chart-circle/circles.min.js' %}"></script>

	<!-- Datatables -->
	<script src="{% static 'core/js/plugin/datatables/datatables.min.js' %}"></script>

	<!-- Bootstrap Notify -->
	<script src="{% static 'core/js/plugin/bootstrap-notify/bootstrap-notify.min.js' %}"></script>

	<!-- jQuery Vector Maps -->
	<script src="{% static 'core/js/plugin/jqvmap/jquery.vmap.min.js' %}"></script>
	<script src="{% static 'core/js/plugin/jqvmap/maps/jquery.vmap.world.js' %}"></script>

	<!-- Sweet Alert -->
	<script src="{% static 'core/js/plugin/sweetalert/sweetalert.min.js' %}"></script>

	<!-- Atlantis JS -->
	<script src="{% static 'core/js/atlantis.min.js' %}"></script>

	{% if request.user.is_authenticated %}
	<script>
		var nav_group_name = '{{ nav_group_name }}';
		var nav_group_item = '{{ nav_group_name }}{{ nav_group_item }}';
        document.querySelector('#' + nav_group_item).classList.add('active');
        document.querySelector('#' + nav_group_name).classList.add('show');
        document.querySelector('#' + nav_group_name + '-nav').classList.add('active');
        document.querySelector('#' + nav_group_name + '-nav').classList.add('submenu');

		function notify(body, level){
			let content = {title: '', message: body, icon: 'fa fa-bell', url: '#', target: '_blank'};
			$.notify(content,{
				type: level,
				allow_dismiss: true,
				showProgressbar: true,
				placement: {from: "top", align: "center"},
				time: 1000,
				delay: 1000,
				template: '<div data-notify="container" class="col-xs-11 col-sm-3 alert alert-{0}" role="alert">' +
					'<button type="button" aria-hidden="true" class="close" data-notify="dismiss">×</button>' +
					'<span data-notify="icon"></span> ' +
					'<span data-notify="message">{2}</span>' +
					'<div class="progress" data-notify="progressbar">' +
						'<div class="progress-bar bg-{0}" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;"></div>' +
					'</div>' +
					'<a href="{3}" target="{4}" data-notify="url"></a>' +
				'</div>'
			});
		}

		{% for message in messages %}
			notify('{{ message }}', '{{ message.tags }}');
		{% endfor %}
	</script>
	{% block script %}{% endblock script %}
	{% endif %}
</body>
</html>

core/templates/core/login.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<!--<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>-->
    <!--<link rel="icon" type="image/png" href="{% static 'login/images/icons/favicon.ico' %}">-->
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form method="POST" class="login100-form validate-form p-l-55 p-r-55 p-b-100 p-t-178">
					{% csrf_token %}
					<span class="login100-form-title">
						Login
					</span>

					{% if form.non_field_errors %}
					<div class="wrap-input100 validate-input m-b-16 text-danger">
						{% for error in form.non_field_errors %}
							<li>{{ error }}</li>
						{% endfor %}
					</div>
					{% endif %}

					<div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input m-b-16" data-validate = "Please enter password">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
					</div>

					<!--<div class="text-right p-t-13 p-b-23">
						<span class="txt1">
							Forgot
						</span>

						<a href="#" class="txt2">
							Username / Password?
						</a>
					</div>-->

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>


<!--===============================================================================================-->
	<script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/js/main.js' %}"></script>

</body>
</html>